 Insert Into estado (cod, nome, sigla) Values(1,'Acre','AC');  
 Insert Into estado (cod, nome, sigla) Values(2,'Alagoas','AL');  
 Insert Into estado (cod, nome, sigla) Values(3,'Amazonas','AM');  
 Insert Into estado (cod, nome, sigla) Values(4,'Amapá','AP');  
 Insert Into estado (cod, nome, sigla) Values(5,'Bahia','BA');  
 Insert Into estado (cod, nome, sigla) Values(6,'Ceará','CE');  
 Insert Into estado (cod, nome, sigla) Values(7,'Distrito Federal','DF');  
 Insert Into estado (cod, nome, sigla) Values(8,'Espírito Santo','ES');  
 Insert Into estado (cod, nome, sigla) Values(9,'Goiás','GO');  
 Insert Into estado (cod, nome, sigla) Values(10,'Maranhão','MA');  
 Insert Into estado (cod, nome, sigla) Values(11,'Minas Gerais','MG');  
 Insert Into estado (cod, nome, sigla) Values(12,'Mato Grosso do Sul','MS');  
 Insert Into estado (cod, nome, sigla) Values(13,'Mato Grosso','MT');  
 Insert Into estado (cod, nome, sigla) Values(14,'Pará','PA');  
 Insert Into estado (cod, nome, sigla) Values(15,'Paraíba','PB');  
 Insert Into estado (cod, nome, sigla) Values(16,'Pernambuco','PE');  
 Insert Into estado (cod, nome, sigla) Values(17,'Piauí','PI');  
 Insert Into estado (cod, nome, sigla) Values(18,'Paraná','PR');  
 Insert Into estado (cod, nome, sigla) Values(19,'Rio de Janeiro','RJ');  
 Insert Into estado (cod, nome, sigla) Values(20,'Rio Grande do Norte','RN');  
 Insert Into estado (cod, nome, sigla) Values(21,'Rondônia','RO');  
 Insert Into estado (cod, nome, sigla) Values(22,'Roraima','RR');  
 Insert Into estado (cod, nome, sigla) Values(23,'Rio Grande do Sul','RS');  
 Insert Into estado (cod, nome, sigla) Values(24,'Santa Catarina','SC');  
 Insert Into estado (cod, nome, sigla) Values(25,'Sergipe','SE');  
 Insert Into estado (cod, nome, sigla) Values(26,'São Paulo','SP');  
 Insert Into estado (cod, nome, sigla) Values(27,'Tocantis','TO'); 